package:
    name: stream_online_viewer
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - matplotlib
        - numpy
        - bsread

build:
  entry_points:
    - stream_online_view_server = stream_online_viewer.start_server:main
    - stream_online_view_stream = stream_online_viewer.start_stream:main